# -*- coding: utf-8 -*-
"""my_math.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/michael-borck/isys2001-worksheets/blob/main/my_math.ipynb

Any Python file you create is a module that you can import. Here is a simple module that has some basic arithmetic functions in it.

This code is very naive. You have no error handling at all, for example. What that means is that you could divide by zero and cause an exception to be thrown. You could also pass incompatible types to these functions, like a string and an integer -- that would cause a different kind of exception to be raised.

However, for learning purposes, this code is adequate.
"""

def add(x, y):
    '''Add two numbers'''
    return x + y

def divide(x, y):
    '''Divide first by second number'''
    return x / y

def multiply(x, y):
    '''Multiple two numbers'''
    return x * y

def subtract(x, y):
    '''Subtract two numbers'''
    return x - y